config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'



  resources :pages do
    resources :lines do
      resources :items
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line.rb
class Line
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps
  include Sizeable

  belongs_to :page
  has_many :items, dependent: :destroy

  field :number, default: 1, required: true
  field :modules

  field :num_of_modules, default: 12, required: true

  field :height, default: Line.line_height

  def height_in_mm
    height.mm
  end

  def num_of_modules
    self.items.sum(:modulen)
  end

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :set_line, only: [:show, :edit, :update, :destroy]

  # GET /lines
  def index
    @page = Page.find(params[:page_id])
    @lines = Line.where(page_id: params[:page_id])
  end

  # GET /lines/1
  def show
  end

  # GET /lines/new
  def new
    @page = Page.find(params[:page_id])
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
    @page = Page.find(params[:page_id])
  end

  # POST /lines
  def create
    @line = Line.new(line_params)
    @page = Page.find(params[:page_id])
    @line.page = @page
    @count = params[:line][:num_of_modules].to_i || 1
    if @line.save
      @count.times do |i|
        item = Item.create(line: @line, number: i + 1)
      end
    redirect_to page_lines_url, notice: 'Regel aangemaakt.'
    else
      render :new
    end
  end

  # PATCH/PUT /lines/1
  def update
    if @line.update(line_params)
      if @line.items.count == 0
        num_of_modules = params[:line][:num_of_modules].to_i

        num_of_modules.times do |i|
          item = Item.create(line: @line, number: i + 1)
        end
      end

      redirect_to page_lines_url, notice: 'Regel gewijzigd.'
    else
      render :edit
    end
  end

  # DELETE /lines/1
  def destroy
    @line.destroy
    redirect_to page_lines_url, notice: 'Regel verwijderd.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def line_params
      params.require(:line).permit(:number, :num_of_modules, :page_id)
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<%= simple_form_for([@page, @line]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :number, as: :integer, label: 'Nummer', input_html: { value: "#{@page.lines.count + 1}" } if params[:action] == "new" %>
    <%= f.input :number, as: :integer, label: 'Nummer' if params[:action] == "edit" %>
  </div>

  <div class="form-inputs">
    <%= f.input :num_of_modules, as: :integer, label: 'Aantal modulen' %>
  </div>

  <div class="form-inputs">
    <%= f.input :height, as: :integer, label: 'Hoogte (mm)' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,"#{f.object.new_record? ? 'Maak Regel' : 'Wijzig Regel'}" %>
  </div>
<% end %>

app/views/lines/edit.html.erb
<h1>Wijzig Regel <%= @line.number %></h1>
<% breadcrumb :line, @line %>

<%= render 'form', line: @line %>

<%= link_to 'Show', page_lines_path(@line.page, @line) %> |
<%= link_to 'Back', page_lines_path %>

app/views/lines/index.html.erb
<%= content_for :title, "Regels van #{@page.title}" %>

<% breadcrumb :lines, @lines %>



<h1>Regels van <%= @page.title %></h1>

<table>
  <thead>
    <tr>
      <th>Nummer</th>
      <th>Aantal Modulen</th>
      <th colspan="2">Hoogte</th>
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.number %></td>
        <td><%= link_to line.items.count, page_line_items_path(line.page, line) %></td>
        <td><%= line.height %> mm</td>
        <td>
          <%= link_to page_lines_path(line) do %><i class="fi-eye"></i><% end %>
          <%= link_to edit_page_line_path(line.page, line) do %><i class="fi-pencil"></i><% end %>
          <%= link_to page_line_path(line.page, line), method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fi-trash"></i><% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nieuwe Regel', new_page_line_path, class: 'button' %>

app/views/lines/new.html.erb
<h1>Nieuwe regel</h1>

<%= render 'form', line: @line %>

<%= link_to 'Terug', page_lines_path %>

app/views/lines/show.html.erb
<% breadcrumb :line, @line %>

<p>
  <strong>Nummer:</strong>
  <%= @line.number %>
</p>

<%= link_to 'Edit', edit_page_line_path(@line.page, @line) %> |
<%= link_to 'Back', page_lines_path %>