config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'



  resources :pages do
    resources :lines do
      resources :items
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_form.html.erb
<% breadcrumb :page, @page %>

<%= simple_form_for(@page) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :project_number, as: :integer, label: 'Project nummer' %>
  </div>

  <div class="form-inputs">
    <%= f.input :title, label: 'Titel' %>
  </div>

  <div class="form-inputs">
    <%= f.input :size, collection: Page.paper_sizes.keys, include_blank: false, label: 'Formaat' %>
  </div>

  <div class="form-inputs">
    <%= f.input :layout, collection: [:portrait, :landscape], include_blank: false, label: 'Layout' %>
  </div>

  <div class="form-inputs">
    <%= f.input :num_of_lines, as: :integer, label: 'Aantal regels' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,"#{f.object.new_record? ? 'Maak Pagina' : 'Wijzig Pagina'}" %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Wijzig <%= @page.title %></h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<% breadcrumb :pages, @pages %>



<h1>Paginas</h1>

<table>
  <thead>
    <tr>
      <th>Project nummer</th>
      <th>Naam</th>
      <th>Formaat</th>
      <th>Layout</th>
      <th colspan="2">Regels</th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.project_number %></td>
        <td><%= page.title %></td>
        <td><%= page.size %></td>
        <td><%= page.layout %></td>
        <td><%= link_to page.lines.count, page_lines_path(page) %></td>
        <td>

          <%= link_to page do %><i class="fi-eye"></i><% end %>
          <%= link_to edit_page_path(page) do %><i class="fi-pencil"></i><% end %>
          <%= link_to page, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fi-trash"></i><% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nieuwe pagina', new_page_path, class: 'button round' %>

app/views/pages/new.html.erb
<div class="alert callout" data-closable>
  <h5>LET OP:</h5>
  <p>
    Voor de standaard maat van 12 modulen dient u de pagina in landscape af te drukken.
  </p>
  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<h1>Nieuwe Pagina</h1>

<%= render 'form', page: @page %>

<%= link_to 'Terug', pages_path %>

app/views/pages/show.html.erb
<% breadcrumb :page, @page %>

<div class="primary callout" data-closable>
  <h5>Formaat: <%= @page.size %><br />
  Layout: <%= @page.layout %></h5>
  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
    <span aria-hidden="true">&times;</span>
  </button>
</div>



<table>
  <thead>
    <tr>
      <th><h3><%= link_to @page.title, edit_page_path(@page) %></h3></th>

      <th colspan="12"></th>

    </tr>
  </thead>
  <tbody>
    <% @lines.each do |line| %>
    <tr>
      <td><%= link_to line.number, page_line_items_path(@page, line) %></td>
      <% line.items.order(:number).each do |item| %>
        <td>
          <%= link_to edit_page_line_item_path(@page, line, item) do %>
            <div style="height:100%;width:100%">
              <%= item.title.blank? ? "<leeg>" : item.title %>
            </div>
          <% end %>
        </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Wijzig', edit_page_path(@page) %> |
<%= link_to 'Terug', pages_path %> |

<!-- <%= link_to 'Print', 'javascript:print()' %> -->
<%= link_to "Maak PDF", page_path(@page, :format => 'pdf') %>