config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'



  resources :pages do
    resources :lines do
      resources :items
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps
  include Sizeable

  belongs_to :line

  has_one :page, through: :line

  field :title, default: "Gr. "
  field :description

  field :number, type: Integer, default: 1

  field :modulen, type: Float, default: 1

  def width_in_mm
    modulen * Item.module_size.mm
  end



end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.where(line_id: params[:line_id]).order_by(number: :asc)
  end

  # GET /items/1
  def show

  end

  # GET /items/new
  def new
    @item = Item.new
    @line = Line.find(params[:line_id])
  end

  # GET /items/1/edit
  def edit

  end

  # POST /items
  def create
    @line = Line.find(params[:line_id])
    @item = Item.new(item_params)
    @item.line = @line

    if @item.save
      redirect_to page_line_items_url, notice: 'Module aangemaakt.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    @index = @line.items.index(@item)
    @num_of_modules = @line.num_of_modules



    if @item.update(item_params)

      redirect_to page_line_items_url, notice: 'Module gewijzigd.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy

    # num_of_modules = @line.num_of_modules
    #
    # if num_of_modules < 12
    #   diff = 12 - num_of_modules
    #
    #   num = [1,2,3,4,5,6,7,8,9,10,11,12] - @line.items.select.pluck(:number)
    #
    #   diff.times do
    #     item = Item.create(line: @line, number: num[0], title: "")
    #   end
    # end

    redirect_to page_line_items_url, notice: 'Module verwijderd.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @page = Page.find(params[:page_id])
      @line = Line.find(params[:line_id])
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:title, :number, :modulen, :line, :description)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<% breadcrumb :item, @item %>

<% unless @item.new_record? %>
  <%= simple_form_for([@page, @line, @item]) do |f| %>
    <%= render 'form_fields', f: f %>
  <% end %>
<% else %>
  <%= simple_form_for(@item, url: page_line_items_path) do |f| %>

    <%= render 'form_fields', f: f %>

  <% end %>
<% end %>

app/views/items/_form_fields.html.erb
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.input :number, as: :integer, label: 'Nummer', input_html: { value: "#{@line.items.count + 1}" } if params[:action] == "new" %>
  <%= f.input :number, as: :integer, label: 'Nummer' if params[:action] == "edit" %>
</div>

<div class="form-inputs">
  <%= f.input :title, label: 'Naam' %>
</div>

<div class="form-inputs">
  <%= f.input :description, label: 'Omschrijving' %>
</div>

<div class="form-inputs">
  <%= f.input :modulen, as: :integer, as: :integer, label: 'Aantal Modulen' %>
</div>

<div class="form-actions">
  <%= f.button :submit,"#{f.object.new_record? ? 'Maak' : 'Wijzig'}" %>
</div>

app/views/items/edit.html.erb
<h1>Wijzig module</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', page_line_item_path(@item.page,@item.line,@item)  %> |
<%= link_to 'Back', page_line_items_path %>

app/views/items/index.html.erb
<% breadcrumb :items, @items %>

<h1>Modulen</h1>

<table>
  <thead>
    <tr>
      <th>Nummer:</th>
      <th>Titel:</th>
      <th>Omschrijving:</th>
      <th>Aantal Modulen:</th>
      <th>Regel:</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.number, edit_page_line_item_path(item.line.page,item.line,item) %></td>
        <td><%= link_to item.title, edit_page_line_item_path(item.line.page,item.line,item) %></td>
        <td><%= item.description %></td>
        <td><%= item.modulen %></td>
        <td><%= item.line.number %></td>
        <td>
          <%= link_to page_line_item_path(item.line.page,item.line,item), method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fi-trash"></i><% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nieuwe module', new_page_line_item_path, class: 'button' %>

app/views/items/new.html.erb
<h1>Nieuwe Module</h1>

<%= render 'form', item: @item %>

<%= link_to 'Terug', page_line_items_path %>

app/views/items/show.html.erb
<% breadcrumb :item, @item %>



<p>
  <strong>Nummer:</strong>
  <%= @item.number %>
</p>
<p>
  <strong>Naam:</strong>
  <%= @item.title %>
</p>

<%= link_to 'Edit', edit_page_line_item_path(@item.page,@item.line,@item) %> |
<%= link_to 'Back', page_line_items_path %>